#!/bin/zsh

if [ ! -d $HOME/.Trash ]; then
    mkdir -p $HOME/.Trash
fi

for i in $@;
do
    # echo "$i"
    if [ $i = $HOME/Desktop/Новая\ папка ]
    then
        echo "\"$i\" нельзя переместить в корзину"
    else
        mv -f $i $HOME/.Trash/
    fi
done
